### ISSUE TITLE
meta: medium-term roadmap (6 months)

### ISSUE THREAD

**Issue by jo3-l** [yagpdb-cc/yagpdb-cc#115]
This details our plans for this repository the next 6 months.

# General plans

- Make the repository friendlier to people just looking to add a CC
- Encourage contributing more
- Revamp existing CCs and add new ones

# Todo list

- [x] Get #90 sorted out ~~and merged~~
- [ ] Database tools
  - Use less CC slots than Crafter (smh crafter)
  - Support JSON for setting values, generally better support for maps and slices
  - e.g. `dbset 0 "test" { "name": "Joe" }`
- [ ] JSON parser-ish snippet
- [ ] Pretty print JSON snippet
- [ ] Leveling v2
  - Support multiple role rewards for a level
  - Remove 200 role reward limit
  - Nicer interface
  - Rank cards, two versions using ImageKit and the other API (API looks worse, but is more reliable)
- [ ] Leveling-redux
  - Version of leveling for "small" servers using a single DB entry and sorted sets
  - ~ 2000-ish members in DB is the max, but we'll provide a migration tool
  - Can support rank without `dbRank`, generally far faster than normal leveling system, even if `dbRank` is out
  - Will feature all other features from leveling v2
- [ ] Starboard v2
  - Limited support for embeds
  - Track top starred members and messages
  - Fix #27
- [ ] Message link v2
- [ ] Counting v2
  - Use mutually exclusive Automodv2 ruleset + CC to ensure users can't run commands
  - Track top counters, generally more fully featured
- [ ] Tic-tac-toe through reactions
- [ ] Connect 4 through reactions
- [ ] Go through the repo and 🧹 old CCs

**Comment by soudblox** [comment]
When will you start and which one will you start first

**Comment by JordiHakimZiyech** [comment]
Joe 2 things
tic-tac-toe is already a custom command made by someone (i dont remember by who) if you want it , let me know on disord, and ill send u the code
2nd thing, can u add economy system as a todo?

**Comment by WickedWizard3588** [comment]
@JordiHakimZiyech DZ made the Tic-Tac-Toe system in his Github, [here is the link](https://github.com/DZ-TM/Yagpdb.xyz/tree/master/Commands/TicTacToeSystem)

**Comment by JordiHakimZiyech** [comment]
> @JordiHakimZiyech DZ made the Tic-Tac-Toe system in his Github, [here is the link](https://github.com/DZ-TM/Yagpdb.xyz/tree/master/Commands/TicTacToeSystem)

yes that one
