### ISSUE TITLE
Meta: Refactor Markdown Files

### ISSUE THREAD

**Issue by l-zeuch** [yagpdb-cc/yagpdb-cc#186]
This issue is to track the status of the `refactor/markdown-files` branch and the documentation files which need rewriting.

Feel free to comment below what is needed, and I will update this issue on regular intervals. Feel also free to add according commits to the `refactor/markdown-files` branch. 

This is the current roadmap:
- [x] Rework the [afk](https://github.com/yagpdb-cc/yagpdb-cc/tree/master/afk) documentation.
- [x] Rework the [suggestion](https://github.com/yagpdb-cc/yagpdb-cc/tree/master/suggestion) documentation
- [x] Work on #49 - Needs feedback.
- [ ] Document the [giveaway](https://github.com/yagpdb-cc/yagpdb-cc/tree/master/giveaway) command appropriately.
- [ ] Annoy @Pedro-Pessoa to get #163 sorted and rework documentation accordingly.
- [ ] Hopefully get #52 sorted, as well - GitHub pages might be worthwhile. I'm sure we can find a team of people willing to work on that.
---
This comment will be updated throughout the process of reworking.

**Comment by l-zeuch** [comment]
Small-ish update:
The afk documentation has been rewritten in f97468b. 
Hit me up when I missed something or you have suggestions on the general layout.

**Comment by l-zeuch** [comment]
The suggestion documentation and the respective leading comment have been reworked in 0a59332 and e5d0c6e. 
As usual, if anything is missing, please let me know, same goes for anything that should be reworked as well.

**Comment by EsenDR** [comment]
Hmm, for the GitHub Pages, if there's plans to do it, feel free to contact me if you'd like me to help out with it. I'm down to help write the documentation on there and work on the site itself 👍.

**Comment by MatiasMFM2001** [comment]
Birthdays: In [README](https://github.com/yagpdb-cc/yagpdb-cc/tree/master/birthday#commands), `setbirthday` has one argument (user). But [real command](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/birthday/birthday.go.tmpl#L60) takes two (date and user, in that order)

**Comment by l-zeuch** [comment]
Thank you for the hint! Pushed a fix 👍🏾

**Comment by MatiasMFM2001** [comment]
You're welcome!
Oh, also applies for [`markdown-files`](https://github.com/yagpdb-cc/yagpdb-cc/tree/refactor/markdown-files/birthday#commands) branch
